import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} h-full antialiased bg-dark`}
    >
      <body className="min-h-full flex flex-col font-sans text-white overflow-x-hidden">
        
        {/* Global Minimalist Navbar */}
        <header className="fixed top-0 left-0 w-full z-50 p-6 md:p-10 flex justify-between items-center pointer-events-none">
          <Link href="/" className="pointer-events-auto">
            <img src="/CondorLens.png" alt="CondorLens" className="w-12 h-auto drop-shadow-[0_0_15px_rgba(0,210,255,0.4)] opacity-80 hover:opacity-100 transition-opacity" />
          </Link>
        </header>

        {children}
      </body>
    </html>
  );
}
